version: '3.4'
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.25.2
    ports:
    - 8090:8080  # Changed host port to 8090 to avoid conflicts
    - 50051:50051
    volumes:
    - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-gpt4all'
      ENABLE_MODULES: 'text2vec-gpt4all'
      GPT4ALL_INFERENCE_API: 'http://text2vec-gpt4all:8080'
      CLUSTER_HOSTNAME: 'node1'
  text2vec-gpt4all:
    image: cr.weaviate.io/semitechnologies/gpt4all-inference:all-MiniLM-L6-v2
    ports:
    - 8081:8080  # Changed host port to 8081 to avoid conflicts
volumes:
  weaviate_data:
